1
SELECT first_name FROM ACTOR
UNION
SELECT first_name FROM CUSTOMER

2
SELECT first_name FROM ACTOR
INTERSECT
SELECT first_name FROM CUSTOMER

3
SELECT first_name FROM ACTOR
EXCEPT
SELECT first_name FROM CUSTOMER

4
SELECT first_name FROM ACTOR
UNION
SELECT first_name FROM CUSTOMER

SELECT first_name FROM ACTOR
EXCEPT ALL
SELECT first_name FROM CUSTOMER